import type { NextPage } from "next"
import Head from "next/head"

import Link from "next/link"
import {getSession, signIn, signOut, useSession} from "next-auth/react"

const Home: NextPage = () => {

const { data: session } = useSession()

console.log(session)

    const getSession = async (e: any) => {
    e.preventDefault()
       await  fetch('api/posts', {method: 'POST'})
    }
    
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>
        Hello
      </h2>


        <div >
            <p
            
            >
                {!session && (
                    <>
              <span >
                You are not signed in
              </span>
                        <button
                            href={`/api/auth/signin`}
                            className=" btn btn-primary"
                            onClick={(e) => {
                                e.preventDefault()
                                signIn()
                            }}
                        >
                            Sign in
                        </button>
                    </>
                )}
                {session?.user && (
                    <>
                        {session.user.image && (
                            <span
                                style={{ backgroundImage: `url('${session.user.image}')` }}
                            
                            />
                        )}
                        <span >
                <small>Signed in as</small>
                <br />
                <strong>{ session.user.name}</strong>
              </span>


                        <button
                            href={`/api/auth/signout`}
                            className=" btn btn-primary"
                            onClick={(e) => {
                                e.preventDefault()
                                signOut()
                            }}
                        >
                            Sign out
                        </button>
                    <button onClick={getSession}>GetSession</button>

                    </>
                )}
            </p>
            {/*<button onClick={testPost}>Get session</button>*/}
        </div>
      
    </>
  );
};

export default Home
