import type { NextPage } from "next"
import Head from "next/head"
import { useSession } from "next-auth/react"


const Home: NextPage = () => {

const { data: session } = useSession()

console.log(session)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>
        Hello
      </h2>
      
    </>
  );
};

export default Home
